FROM daangn/faiss

RUN apt-get --allow-releaseinfo-change update && apt-get install -y gcc

RUN pip install --upgrade pip
RUN pip install setuptools wheel
RUN pip install flask==2.2.2 \
    requests==2.25.1 \
    redis==4.4.0 \
    numpy==1.21.6

WORKDIR /app
COPY ./ /app/

ENV FLASK_APP /app/main.py

EXPOSE 5000
CMD flask run --host 0.0.0.0 --port 5000