FROM tensorflow/serving:latest

RUN apt update
RUN apt-get install -y wget tar
RUN wget https://tfhub.dev/google/universal-sentence-encoder-large/5?tf-hub-format=compressed -O /models/use-large.tar.gz
RUN mkdir -p /models/use-large/1 && \
    tar -xvf /models/use-large.tar.gz -C /models/use-large/1 && \
    rm -rf /models/use-large.tar.gz

EXPOSE 8501
CMD ["tensorflow_model_server", "--port=8500", "--rest_api_port=8501", "--model_name=use-large", "--model_base_path=/models/use-large"]